In [10]:
import torch
from pytorch_pretrained_bert import BertTokenizer, BertModel, BertForMaskedLM

# OPTIONAL: if you want to have more information on what's happening, activate the logger as follows
import logging
logging.basicConfig(level=logging.INFO)

# Load pre-trained model tokenizer (vocabulary)
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

INFO:pytorch_pretrained_bert.tokenization:loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /home/ubuntu/.pytorch_pretrained_bert/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084


In [38]:
x = torch.rand(16, 50)
y = torch.randn(16, 50)

In [41]:
torch.add(x,y)

tensor([[-3.6285e-01,  2.1353e+00,  1.3635e+00,  4.5509e-01,  2.9611e+00,
         -3.4002e-01, -1.1033e-01,  1.7823e+00, -2.0549e+00,  1.8160e+00,
          9.1798e-01, -1.3519e-02, -3.8176e-01, -2.5720e-01,  8.2993e-01,
         -3.7678e-01,  8.3064e-01,  4.0142e-02, -7.2786e-01, -6.3016e-01,
         -1.5183e+00,  5.8611e-01,  8.8385e-01,  1.4353e+00,  6.1886e-01,
          1.8254e+00,  1.1450e-01,  1.1755e+00, -2.4351e-01, -8.3609e-01,
          1.2840e+00,  3.7152e-01,  4.8241e-01,  7.6734e-01, -7.7852e-01,
          1.0632e+00,  4.5449e-01,  1.0960e+00, -3.1369e-01,  1.8546e+00,
          2.6766e+00, -1.2334e+00,  2.8940e+00,  1.6867e+00,  1.7893e+00,
         -1.2308e+00,  5.0151e-01,  1.2479e+00,  5.3214e-01,  7.6085e-01],
        [-1.5900e-01, -4.4692e-01, -5.1216e-01,  5.0966e-01,  1.6048e+00,
         -4.3329e-01,  6.2193e-01,  2.0520e+00, -1.5548e+00,  1.4388e+00,
          5.8363e-01,  6.0960e-01,  7.5370e-01, -8.0622e-01,  3.9439e-01,
         -1.3045e+00,  2.1670e+00, -1

In [32]:
a = [1]*8

In [33]:
0.5*a

TypeError: can't multiply sequence by non-int of type 'float'

In [27]:
torch.mul(x,y)

tensor([[-1.3426e+00,  1.1839e-01, -1.2218e+00, -2.2162e-01, -1.9100e-01,
          1.2570e+00, -3.4034e-02, -1.2746e-01, -8.2249e-01, -8.3497e-01,
         -4.0989e-01, -2.6595e-01, -3.9027e-01,  4.4154e-02,  1.0319e+00,
         -7.3006e-03,  5.2942e-01, -8.0097e-03,  3.3872e-01,  2.9605e-01,
         -1.1599e-01,  7.2672e-02, -3.3293e-01, -1.4528e-01,  7.9535e-01,
         -2.3816e-01, -7.0218e-01, -7.1539e-01, -2.1532e-01, -4.5214e-01,
          2.6242e-01,  1.0639e-01, -4.5165e-01, -7.9665e-01,  3.4077e-01,
          2.2819e-01,  5.9807e-02, -4.3522e-01, -1.0333e-01, -6.6305e-01,
          1.2011e+00,  8.8361e-01, -1.1895e-01,  8.2189e-02, -2.1766e-01,
         -1.1039e+00, -1.2325e-01, -5.1053e-01,  2.3537e-01,  8.8695e-02],
        [-1.2546e-01,  1.1666e-01,  4.7909e-01, -1.3894e+00, -6.3668e-03,
          5.9588e-01,  9.1368e-01,  7.7995e-02,  3.0418e-01,  1.2657e-01,
         -1.4624e-02, -2.8955e-01,  7.0085e-01, -2.3118e-01, -2.5329e-01,
          7.4412e-01,  5.0046e-01,  3

In [35]:
x = x.to(device)

In [37]:
x = x.data
x = x.cpu()
x = x.numpy()

In [39]:
str(x)

'24'

In [6]:
z = torch.cat((x, x), 0)

In [7]:
z.shape

torch.Size([1536, 1])

In [1]:
from __future__ import print_function, division

import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim import lr_scheduler
import numpy as np
import torchvision
from torchvision import datasets, models, transforms
import matplotlib.pyplot as plt
import time
import os
import copy
from torch.utils.data import Dataset, DataLoader
from PIL import Image
from random import randrange
import torch.nn.functional as F
import pandas as pd

In [7]:
text =statements['train'][2]

In [8]:
len(text.split(' '))

19

In [11]:
zz = tokenizer.tokenize(text)

In [13]:
len(zz)

22

In [2]:
train_path = '/home/ubuntu/fake_news/LIAR-PLUS/dataset/train2.tsv'
test_path = '/home/ubuntu/fake_news/LIAR-PLUS/dataset/test2.tsv'
val_path = '/home/ubuntu/fake_news/LIAR-PLUS/dataset/val2.tsv'

In [35]:
train_df = pd.read_csv(train_path, sep="\t", header=None)
test_df = pd.read_csv(test_path, sep="\t", header=None)
val_df = pd.read_csv(val_path, sep="\t", header=None)

# Fill nan (empty boxes) with 0
train_df = train_df.fillna('None')
test_df = test_df.fillna('None')
val_df = val_df.fillna('None')

In [36]:
train = train_df.values
test = test_df.values
val = val_df.values

In [37]:
labels = {'train':[train[i][2] for i in range(len(train))], 'test':[test[i][2] for i in range(len(test))], 'val':[val[i][2] for i in range(len(val))]}
statements = {'train':[train[i][3] for i in range(len(train))], 'test':[test[i][3] for i in range(len(test))], 'val':[val[i][3] for i in range(len(val))]}
subjects = {'train':[train[i][4] for i in range(len(train))], 'test':[test[i][4] for i in range(len(test))], 'val':[val[i][4] for i in range(len(val))]}
speakers = {'train':[train[i][5] for i in range(len(train))], 'test':[test[i][5] for i in range(len(test))], 'val':[val[i][5] for i in range(len(val))]}
jobs = {'train':[train[i][6] for i in range(len(train))], 'test':[test[i][6] for i in range(len(test))], 'val':[val[i][6] for i in range(len(val))]}
states = {'train':[train[i][7] for i in range(len(train))], 'test':[test[i][7] for i in range(len(test))], 'val':[val[i][7] for i in range(len(val))]}
affiliations = {'train':[train[i][8] for i in range(len(train))], 'test':[test[i][8] for i in range(len(test))], 'val':[val[i][8] for i in range(len(val))]}
credits = {'train':[train[i][9:14] for i in range(len(train))], 'test':[test[i][9:14] for i in range(len(test))], 'val':[val[i][9:14] for i in range(len(val))]}
contexts = {'train':[train[i][14] for i in range(len(train))], 'test':[test[i][14] for i in range(len(test))], 'val':[val[i][14] for i in range(len(val))]}
justification = {'train':[train[i][15] for i in range(len(train))], 'test':[test[i][15] for i in range(len(test))], 'val':[val[i][15] for i in range(len(val))]}

In [62]:
ma = 256
p = 0
for i in range(len(train)):
    #print(justification['val'][i])
    if len(justification['train'][i].split(' ')) > ma:
    
        print(len(justification['train'][i].split(' ')))
        p = p+1

842
508
662
289
3030
3025
709
1974
2966
821
708
271
544
260
1094
273
258
268
370
452
260
276
318
491


In [63]:
p

24

In [52]:
speaker['train']

['dwayne-bohac',
 'scott-surovell',
 'barack-obama',
 'blog-posting',
 'charlie-crist',
 'robin-vos',
 'republican-party-texas',
 'barack-obama',
 'oregon-lottery',
 'duey-stroebel',
 'robert-menendez',
 'bernie-s',
 'mitt-romney',
 'doonesbury',
 'george-will',
 'bernie-s',
 'barack-obama',
 'national-republican-congressional-committee',
 'gwen-moore',
 'jack-lew',
 'dennis-richardson',
 'eric-bolling',
 'hillary-clinton',
 'greater-wisconsin-political-fund',
 'planned-parenthood-action-fund',
 'nancy-pelosi',
 'hillary-clinton',
 'ted-nugent',
 'pamela-geller',
 'peter-kinder',
 'hillary-clinton',
 'nicholas-kettle',
 'shelley-moore-capito',
 'rick-scott',
 'tom-cotton',
 'ted-cruz',
 'lee-leffingwell',
 'north-korea',
 'walking-dead',
 'kelly-ayotte',
 'marco-rubio',
 'keep-promise-1-pac',
 'national-republican-congressional-committee',
 'rachel-maddow',
 'jerry-patterson',
 'bernie-s',
 'chain-email',
 'john-boehner',
 'katrina-pierson',
 'blog-posting',
 'rick-perry',
 'national-r

In [48]:
# Preparing meta data

#credit['train'][2]

metadata = {'train':[0]*len(train), 'val':[0]*len(val), 'test':[0]*len(test)}

for i in range(len(train)):
    subject = subjects['train'][i]
    if subject == 0:
        subject = 'None'
        
    #print(subject)
    
    speaker = speakers['train'][i]
    if speaker == 0:
        speaker = 'None'
        
    #print(speaker)
    
    job = jobs['train'][i]
    if job == 0:
        job = 'None'
        
    #print(job)
    
    state = states['train'][i]
    if state == 0:
        state = 'None'
    #print(state)
    affiliation = affiliations['train'][i]
    if affiliation == 0:
        affiliation = 'None'
    #print(affiliation)
    context = contexts['train'][i]
    if context == 0 :
        context = 'None'
    #print(context)
        
    meta = subject + ' ' + speaker + ' ' + job + ' ' + state + ' ' + affiliation + ' ' + context
    
    metadata['train'][i] = meta
    
for i in range(len(val)):
    subject = subjects['val'][i]
    if subject == 0:
        subject = 'None'
        
    #print(subject)
    
    speaker = speakers['val'][i]
    if speaker == 0:
        speaker = 'None'
        
    #print(speaker)
    
    job = jobs['val'][i]
    if job == 0:
        job = 'None'
        
    #print(job)
    
    state = states['val'][i]
    if state == 0:
        state = 'None'
    #print(state)
    affiliation = affiliations['val'][i]
    if affiliation == 0:
        affiliation = 'None'
    #print(affiliation)
    context = contexts['val'][i]
    if context == 0 :
        context = 'None'
    #print(context)
        
    meta = subject + ' ' + speaker + ' ' + job + ' ' + state + ' ' + affiliation + ' ' + context
    
    metadata['val'][i] = meta
    
for i in range(len(test)):
    subject = subjects['test'][i]
    if subject == 0:
        subject = 'None'
        
    #print(subject)
    
    speaker = speakers['test'][i]
    if speaker == 0:
        speaker = 'None'
        
    #print(speaker)
    
    job = jobs['test'][i]
    if job == 0:
        job = 'None'
        
    #print(job)
    
    state = states['test'][i]
    if state == 0:
        state = 'None'
    #print(state)
    affiliation = affiliations['test'][i]
    if affiliation == 0:
        affiliation = 'None'
    #print(affiliation)
    context = contexts['test'][i]
    if context == 0 :
        context = 'None'
    #print(context)
        
    meta = subject + ' ' + speaker + ' ' + job + ' ' + state + ' ' + affiliation + ' ' + context
    
    metadata['test'][i] = meta

In [62]:
metadata['test']

['immigration rick-perry Governor Texas republican Radio interview',
 'jobs katrina-shankland State representative Wisconsin democrat a news conference',
 "military,veterans,voting-record donald-trump President-Elect New York republican comments on ABC's This Week.",
 'medicare,message-machine-2012,campaign-advertising rob-cornilles consultant Oregon republican a radio show',
 'campaign-finance,legal-issues,campaign-advertising state-democratic-party-wisconsin None Wisconsin democrat a web video',
 'federal-budget,pensions,retirement brendan-doherty None Rhode Island republican a campaign website',
 'county-budget,county-government,education,taxes stand-children-tennessee Child and education advocacy organization. Tennessee none in a post on Facebook.',
 'economy,stimulus john-boehner Speaker of the House of Representatives Ohio republican a press release.',
 'gays-and-lesbians,marriage sean-patrick-maloney Congressman for NY-18 New York democrat a speech at the Democratic National Con

In [11]:
# Credit score calculation
credit_score = {'train':[0]*len(train), 'val':[0]*len(val), 'test':[0]*len(test)}
for i in range(len(train)):
    credit = credits['train'][i]
    if sum(credit) == 0:
        score = 0.5
    else:
        score = (credit[3]*0.2 + credit[2]*0.5 + credit[0]*0.75 + credit[1]*0.9 + credit[4]*1)/(sum(credit))
    credit_score['train'][i] = score
    
for i in range(len(val)):
    credit = credits['val'][i]
    if sum(credit) == 0:
        score = 0.5
    else:
        score = (credit[3]*0.2 + credit[2]*0.5 + credit[0]*0.75 + credit[1]*0.9 + credit[4]*1)/(sum(credit))
    credit_score['val'][i] = score
    
for i in range(len(test)):
    credit = credits['test'][i]
    if sum(credit) == 0:
        score = 0.5
    else:
        score = (credit[3]*0.2 + credit[2]*0.5 + credit[0]*0.75 + credit[1]*0.9 + credit[4]*1)/(sum(credit))
    credit_score['test'][i] = score

In [ ]:
for i in range(len(test)):
    credit = credits['test'][i]
    if sum(credit) == 0:
        score = 0.5
    else:
        score = (credit[3]*0.2 + credit[2]*0.5 + credit[0]*0.75 + credit[1]*0.9 + credit[4]*1)/(sum(credit))
    credit_score['test'][i] = score

In [51]:
credit_score['train']

[0.9,
 0.35,
 0.5031712473572939,
 0.8826923076923077,
 0.5407692307692308,
 0.5181818181818182,
 0.5833333333333334,
 0.5031712473572939,
 0.75,
 0.2,
 0.5687500000000001,
 0.46774193548387094,
 0.61875,
 0.3,
 0.6431818181818182,
 0.46774193548387094,
 0.5031712473572939,
 0.7208333333333333,
 0.63,
 0.55,
 0.6428571428571429,
 0.62,
 0.5104072398190046,
 0.6954545454545454,
 0.75,
 0.6711538461538461,
 0.5104072398190046,
 0.75,
 0.7,
 0.6,
 0.5104072398190046,
 0.75,
 0.825,
 0.573076923076923,
 0.6499999999999999,
 0.6846846846846847,
 0.4916666666666667,
 0.5,
 1.0,
 0.46249999999999997,
 0.5763565891472868,
 0.7,
 0.7208333333333333,
 0.6130434782608696,
 0.4583333333333333,
 0.46774193548387094,
 0.9125,
 0.7278846153846155,
 1.0,
 0.8826923076923077,
 0.651048951048951,
 0.7216666666666666,
 0.7441176470588236,
 0.475,
 0.7583333333333333,
 0.5,
 0.5,
 0.7476993865030674,
 0.6113013698630136,
 0.2,
 0.4428571428571429,
 0.65125,
 0.75,
 0.475,
 0.9500000000000001,
 0.75,
 0.61

In [12]:
def to_onehot(a):
    a_cat = [0]*len(a)
    for i in range(len(a)):
        if a[i]=='true':
            a_cat[i] = [1,0,0,0,0,0]
        elif a[i]=='mostly-true':
            a_cat[i] = [0,1,0,0,0,0]
        elif a[i]=='half-true':
            a_cat[i] = [0,0,1,0,0,0]
        elif a[i]=='barely-true':
            a_cat[i] = [0,0,0,1,0,0]
        elif a[i]=='false':
            a_cat[i] = [0,0,0,0,1,0]
        elif a[i]=='pants-fire':
            a_cat[i] = [0,0,0,0,0,1]
        else:
            print('Incorrect label')
    return a_cat

def to_onehot(a):
    a_cat = [0]*len(a)
    for i in range(len(a)):
        if a[i]=='true':
            a_cat[i] = [1,0]
        elif a[i]=='mostly-true':
            a_cat[i] = [1,0]
        elif a[i]=='half-true':
            a_cat[i] = [1,0]
        elif a[i]=='barely-true':
            a_cat[i] = [0,1]
        elif a[i]=='false':
            a_cat[i] = [0,1]
        elif a[i]=='pants-fire':
            a_cat[i] = [0,1]
        else:
            print('Incorrect label')
    return a_cat

In [13]:
labels_onehot = {'train':to_onehot(labels['train']), 'test':to_onehot(labels['test']), 'val':to_onehot(labels['val'])}

In [17]:
class BertLayerNorm(nn.Module):
        def __init__(self, hidden_size, eps=1e-12):
            """Construct a layernorm module in the TF style (epsilon inside the square root).
            """
            super(BertLayerNorm, self).__init__()
            self.weight = nn.Parameter(torch.ones(hidden_size))
            self.bias = nn.Parameter(torch.zeros(hidden_size))
            self.variance_epsilon = eps

        def forward(self, x):
            u = x.mean(-1, keepdim=True)
            s = (x - u).pow(2).mean(-1, keepdim=True)
            x = (x - u) / torch.sqrt(s + self.variance_epsilon)
            return self.weight * x + self.bias
        

class BertForSequenceClassification(nn.Module):
    """BERT model for classification.
    This module is composed of the BERT model with a linear layer on top of
    the pooled output.
    Params:
        `config`: a BertConfig class instance with the configuration to build a new model.
        `num_labels`: the number of classes for the classifier. Default = 2.
    Inputs:
        `input_ids`: a torch.LongTensor of shape [batch_size, sequence_length]
            with the word token indices in the vocabulary. Items in the batch should begin with the special "CLS" token. (see the tokens preprocessing logic in the scripts
            `extract_features.py`, `run_classifier.py` and `run_squad.py`)
        `token_type_ids`: an optional torch.LongTensor of shape [batch_size, sequence_length] with the token
            types indices selected in [0, 1]. Type 0 corresponds to a `sentence A` and type 1 corresponds to
            a `sentence B` token (see BERT paper for more details).
        `attention_mask`: an optional torch.LongTensor of shape [batch_size, sequence_length] with indices
            selected in [0, 1]. It's a mask to be used if the input sequence length is smaller than the max
            input sequence length in the current batch. It's the mask that we typically use for attention when
            a batch has varying length sentences.
        `labels`: labels for the classification output: torch.LongTensor of shape [batch_size]
            with indices selected in [0, ..., num_labels].
    Outputs:
        if `labels` is not `None`:
            Outputs the CrossEntropy classification loss of the output with the labels.
        if `labels` is `None`:
            Outputs the classification logits of shape [batch_size, num_labels].
    Example usage:
    ```python
    # Already been converted into WordPiece token ids
    input_ids = torch.LongTensor([[31, 51, 99], [15, 5, 0]])
    input_mask = torch.LongTensor([[1, 1, 1], [1, 1, 0]])
    token_type_ids = torch.LongTensor([[0, 0, 1], [0, 1, 0]])
    config = BertConfig(vocab_size_or_config_json_file=32000, hidden_size=768,
        num_hidden_layers=12, num_attention_heads=12, intermediate_size=3072)
    num_labels = 2
    model = BertForSequenceClassification(config, num_labels)
    logits = model(input_ids, token_type_ids, input_mask)
    ```
    """
    def __init__(self, num_labels=2): # Change number of labels here.
        super(BertForSequenceClassification, self).__init__()
        self.num_labels = num_labels
        self.bert = BertModel.from_pretrained('bert-base-uncased')
        self.dropout = nn.Dropout(config.hidden_dropout_prob)
        self.classifier = nn.Linear(config.hidden_size*3, num_labels)
        #self.fc1 = nn.Linear(config.hidden_size*2, 512)
        nn.init.xavier_normal_(self.classifier.weight)
        
    '''def forward_once(self, x):
        # Forward pass 
        output = self.cnn1(x)
        output = output.view(output.size()[0], -1)
        output = self.fc1(output)
        return output'''
        
    def forward_once(self, input_ids, token_type_ids=None, attention_mask=None, labels=None):
        _, pooled_output = self.bert(input_ids, token_type_ids, attention_mask, output_all_encoded_layers=False)
        pooled_output = self.dropout(pooled_output)
        #logits = self.classifier(pooled_output)

        return pooled_output
    
    def forward(self, input_ids1, input_ids2, input_ids3, credit_sc):
        # forward pass of input 1
        output1 = self.forward_once(input_ids1, token_type_ids=None, attention_mask=None, labels=None)
        # forward pass of input 2
        output2 = self.forward_once(input_ids2, token_type_ids=None, attention_mask=None, labels=None)
        
        output3 = self.forward_once(input_ids3, token_type_ids=None, attention_mask=None, labels=None)
        
        out = torch.cat((output1, output2, output3), 1)
        
        # Multiply the credit score with the output after concatnation
        
        out = torch.mul(credit_sc, out)
        
        #out = self.fc1(out)
        logits = self.classifier(out)
        
        return logits
    
    def freeze_bert_encoder(self):
        for param in self.bert.parameters():
            param.requires_grad = False
    
    def unfreeze_bert_encoder(self):
        for param in self.bert.parameters():
            param.requires_grad = True

In [20]:
from pytorch_pretrained_bert import BertConfig

config = BertConfig(vocab_size_or_config_json_file=32000, hidden_size=768,
        num_hidden_layers=12, num_attention_heads=12, intermediate_size=3072)

num_labels = 2
model = BertForSequenceClassification(num_labels)

# Convert inputs to PyTorch tensors
tokens_tensor = torch.tensor([tokenizer.convert_tokens_to_ids(zz)])

logits = model(tokens_tensor, tokens_tensor, tokens_tensor, x)

INFO:pytorch_pretrained_bert.modeling:loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz from cache at /home/ubuntu/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba
INFO:pytorch_pretrained_bert.modeling:extracting archive file /home/ubuntu/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba to temp dir /tmp/tmpu2foyag2
INFO:pytorch_pretrained_bert.modeling:Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 30522
}



In [21]:
tokens_tensor

tensor([[ 2054,  2003,  1037, 16405, 25619]])

In [22]:
logits

tensor([[-0.2923,  0.2326]], grad_fn=<AddmmBackward>)

In [16]:
import pandas as pd

dat = pd.read_csv('/home/ubuntu/fake_news/custom_bert_pipeline/IMDB Dataset.csv')

In [17]:
dat.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [18]:
zz = tokenizer.tokenize(dat.review[1])
z1z = tokenizer.tokenize(dat.review[3])

[zz,z1z ]

[['a',
  'wonderful',
  'little',
  'production',
  '.',
  '<',
  'br',
  '/',
  '>',
  '<',
  'br',
  '/',
  '>',
  'the',
  'filming',
  'technique',
  'is',
  'very',
  'una',
  '##ss',
  '##uming',
  '-',
  'very',
  'old',
  '-',
  'time',
  '-',
  'bbc',
  'fashion',
  'and',
  'gives',
  'a',
  'comforting',
  ',',
  'and',
  'sometimes',
  'discomfort',
  '##ing',
  ',',
  'sense',
  'of',
  'realism',
  'to',
  'the',
  'entire',
  'piece',
  '.',
  '<',
  'br',
  '/',
  '>',
  '<',
  'br',
  '/',
  '>',
  'the',
  'actors',
  'are',
  'extremely',
  'well',
  'chosen',
  '-',
  'michael',
  'sheen',
  'not',
  'only',
  '"',
  'has',
  'got',
  'all',
  'the',
  'polar',
  '##i',
  '"',
  'but',
  'he',
  'has',
  'all',
  'the',
  'voices',
  'down',
  'pat',
  'too',
  '!',
  'you',
  'can',
  'truly',
  'see',
  'the',
  'seam',
  '##less',
  'editing',
  'guided',
  'by',
  'the',
  'references',
  'to',
  'williams',
  "'",
  'diary',
  'entries',
  ',',
  'not',
  'only

In [19]:
zzz = tokenizer.convert_tokens_to_ids(zz)
zzzz = tokenizer.convert_tokens_to_ids(z1z)

In [20]:
zzz

[1037,
 6919,
 2210,
 2537,
 1012,
 1026,
 7987,
 1013,
 1028,
 1026,
 7987,
 1013,
 1028,
 1996,
 7467,
 6028,
 2003,
 2200,
 14477,
 4757,
 24270,
 1011,
 2200,
 2214,
 1011,
 2051,
 1011,
 4035,
 4827,
 1998,
 3957,
 1037,
 16334,
 1010,
 1998,
 2823,
 17964,
 2075,
 1010,
 3168,
 1997,
 15650,
 2000,
 1996,
 2972,
 3538,
 1012,
 1026,
 7987,
 1013,
 1028,
 1026,
 7987,
 1013,
 1028,
 1996,
 5889,
 2024,
 5186,
 2092,
 4217,
 1011,
 2745,
 20682,
 2025,
 2069,
 1000,
 2038,
 2288,
 2035,
 1996,
 11508,
 2072,
 1000,
 2021,
 2002,
 2038,
 2035,
 1996,
 5755,
 2091,
 6986,
 2205,
 999,
 2017,
 2064,
 5621,
 2156,
 1996,
 25180,
 3238,
 9260,
 8546,
 2011,
 1996,
 7604,
 2000,
 3766,
 1005,
 9708,
 10445,
 1010,
 2025,
 2069,
 2003,
 2009,
 2092,
 4276,
 1996,
 3666,
 2021,
 2009,
 2003,
 1037,
 27547,
 2135,
 2517,
 1998,
 2864,
 3538,
 1012,
 1037,
 3040,
 3993,
 2537,
 2055,
 2028,
 1997,
 1996,
 2307,
 3040,
 1005,
 1055,
 1997,
 4038,
 1998,
 2010,
 2166,
 1012,
 1026,
 7987,
 101

In [21]:
tokens_tensor = torch.tensor([zzz,zzz])

In [22]:
tokens_tensor

tensor([[ 1037,  6919,  2210,  2537,  1012,  1026,  7987,  1013,  1028,  1026,
          7987,  1013,  1028,  1996,  7467,  6028,  2003,  2200, 14477,  4757,
         24270,  1011,  2200,  2214,  1011,  2051,  1011,  4035,  4827,  1998,
          3957,  1037, 16334,  1010,  1998,  2823, 17964,  2075,  1010,  3168,
          1997, 15650,  2000,  1996,  2972,  3538,  1012,  1026,  7987,  1013,
          1028,  1026,  7987,  1013,  1028,  1996,  5889,  2024,  5186,  2092,
          4217,  1011,  2745, 20682,  2025,  2069,  1000,  2038,  2288,  2035,
          1996, 11508,  2072,  1000,  2021,  2002,  2038,  2035,  1996,  5755,
          2091,  6986,  2205,   999,  2017,  2064,  5621,  2156,  1996, 25180,
          3238,  9260,  8546,  2011,  1996,  7604,  2000,  3766,  1005,  9708,
         10445,  1010,  2025,  2069,  2003,  2009,  2092,  4276,  1996,  3666,
          2021,  2009,  2003,  1037, 27547,  2135,  2517,  1998,  2864,  3538,
          1012,  1037,  3040,  3993,  2537,  2055,  

In [23]:
logits = model(tokens_tensor)
logits


tensor([[-0.2868, -0.2532,  0.2102,  0.2264, -0.3351, -1.7115],
        [ 0.5625,  0.3654,  0.6102,  0.2430, -0.0879, -1.3481]],
       grad_fn=<AddmmBackward>)

In [23]:
import torch.nn.functional as F

F.softmax(logits,dim=1)

tensor([[0.6739, 0.3261]], grad_fn=<SoftmaxBackward>)

In [25]:
'''from sklearn.model_selection import train_test_split
X = dat['review']
y = dat['sentiment']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=42)'''

"from sklearn.model_selection import train_test_split\nX = dat['review']\ny = dat['sentiment']\n\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=42)"

In [26]:
'''X_train = X_train.values.tolist()
X_test = X_test.values.tolist()

y_train = pd.get_dummies(y_train).values.tolist()
y_test = pd.get_dummies(y_test).values.tolist()'''

'X_train = X_train.values.tolist()\nX_test = X_test.values.tolist()\n\ny_train = pd.get_dummies(y_train).values.tolist()\ny_test = pd.get_dummies(y_test).values.tolist()'

In [24]:
X_train = statements['train']
y_train = labels_onehot['train']

X_test = statements['val']
y_test = labels_onehot['val']

In [25]:
max_seq_length = 256
class text_dataset(Dataset):
    def __init__(self,x_y_list, transform=None):
        
        self.x_y_list = x_y_list
        self.transform = transform
        
    def __getitem__(self,index):
        
        tokenized_review = tokenizer.tokenize(self.x_y_list[0][index])
        
        if len(tokenized_review) > max_seq_length:
            tokenized_review = tokenized_review[:max_seq_length]
            
        ids_review  = tokenizer.convert_tokens_to_ids(tokenized_review)

        padding = [0] * (max_seq_length - len(ids_review))
        
        ids_review += padding
        
        assert len(ids_review) == max_seq_length
        
        #print(ids_review)
        ids_review = torch.tensor(ids_review)
        
        sentiment = self.x_y_list[1][index] # color        
        list_of_labels = [torch.from_numpy(np.array(sentiment))]
        
        
        return ids_review, list_of_labels[0]
    
    def __len__(self):
        return len(self.x_y_list[0])

In [26]:
batch_size = 16

train_lists = [X_train, y_train]
test_lists = [X_test, y_test]

training_dataset = text_dataset(x_y_list = train_lists )

test_dataset = text_dataset(x_y_list = test_lists )

dataloaders_dict = {'train': torch.utils.data.DataLoader(training_dataset, batch_size=batch_size, shuffle=True, num_workers=0),
                   'val':torch.utils.data.DataLoader(test_dataset, batch_size=batch_size, shuffle=True, num_workers=0)
                   }
dataset_sizes = {'train':len(train_lists[0]),
                'val':len(test_lists[0])}

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

cuda:0


In [30]:
def train_model(model, criterion, optimizer, scheduler, num_epochs=25):
    since = time.time()
    print('starting')
    best_model_wts = copy.deepcopy(model.state_dict())
    best_loss = 100

    for epoch in range(num_epochs):
        print('Epoch {}/{}'.format(epoch, num_epochs - 1))
        print('-' * 10)

        # Each epoch has a training and validation phase
        for phase in ['train', 'val']:
            if phase == 'train':
                scheduler.step()
                model.train()  # Set model to training mode
            else:
                model.eval()   # Set model to evaluate mode

            running_loss = 0.0
            
            sentiment_corrects = 0
            
            
            # Iterate over data.
            for inputs, sentiment in dataloaders_dict[phase]:
                #inputs = inputs
                #print(len(inputs),type(inputs),inputs)
                #inputs = torch.from_numpy(np.array(inputs)).to(device) 
                inputs = inputs.to(device) 

                sentiment = sentiment.to(device)
                
                # zero the parameter gradients
                optimizer.zero_grad()

                # forward
                # track history if only in train
                with torch.set_grad_enabled(phase == 'train'):
                    #print(inputs)
                    outputs = model(inputs)

                    outputs = F.softmax(outputs,dim=1)
                    
                    loss = criterion(outputs, torch.max(sentiment.float(), 1)[1])
                    # backward + optimize only if in training phase
                    if phase == 'train':
                        
                        loss.backward()
                        optimizer.step()

                # statistics
                running_loss += loss.item() * inputs.size(0)

                
                sentiment_corrects += torch.sum(torch.max(outputs, 1)[1] == torch.max(sentiment, 1)[1])

                
            epoch_loss = running_loss / dataset_sizes[phase]

            
            sentiment_acc = sentiment_corrects.double() / dataset_sizes[phase]

            print('{} total loss: {:.4f} '.format(phase,epoch_loss ))
            print('{} sentiment_acc: {:.4f}'.format(
                phase, sentiment_acc))

            if phase == 'val' and epoch_loss < best_loss:
                print('saving with loss of {}'.format(epoch_loss),
                      'improved over previous {}'.format(best_loss))
                best_loss = epoch_loss
                best_model_wts = copy.deepcopy(model.state_dict())
                torch.save(model.state_dict(), 'bert_model_test.pth')


        print()

    time_elapsed = time.time() - since
    print('Training complete in {:.0f}m {:.0f}s'.format(
        time_elapsed // 60, time_elapsed % 60))
    print('Best val Acc: {:4f}'.format(float(best_loss)))

    # load best model weights
    model.load_state_dict(best_model_wts)
    return model

In [31]:
model.to(device)

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): BertLayerNorm()
      (dropout): Dropout(p=0.1)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): BertLayerNorm()
              (dropout): Dropout(p=0.1)
            )
          )
          (intermediat

In [32]:
lrlast = .001
lrmain = .00001
optim1 = optim.Adam(
    [
        {"params":model.bert.parameters(),"lr": lrmain},
        {"params":model.classifier.parameters(), "lr": lrlast},
       
   ])

#optim1 = optim.Adam(model.parameters(), lr=0.001)#,momentum=.9)
# Observe that all parameters are being optimized
optimizer_ft = optim1
criterion = nn.CrossEntropyLoss()

# Decay LR by a factor of 0.1 every 7 epochs
exp_lr_scheduler = lr_scheduler.StepLR(optimizer_ft, step_size=3, gamma=0.1)

In [ ]:
model_ft1 = train_model(model, criterion, optimizer_ft, exp_lr_scheduler,num_epochs=10)

starting
Epoch 0/9
----------


In [52]:
from pathlib import Path

In [53]:
home = str(Path.home())

In [54]:
home

'/home/ubuntu'